# Generated by Django 5.2.11 on 2026-02-22 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('BEAN', '咖啡豆'), ('DAIRY', '奶制品'), ('FOOD', '其他食品原料'), ('NON_FOOD', '非食品耗材')], max_length=20, verbose_name='物料类型')),
                ('name', models.CharField(max_length=100, verbose_name='物料名称')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='单价/价格')),
                ('quantity', models.PositiveIntegerField(help_text='豆子单位为克，奶制品为盒，其他为个', verbose_name='数量')),
                ('roast_level', models.CharField(blank=True, choices=[('DARK', '深烘'), ('MEDIUM', '中烘'), ('LIGHT', '浅烘')], max_length=10, null=True, verbose_name='烘焙程度（仅咖啡豆）')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='到期时间（仅奶制品）')),
            ],
            options={
                'verbose_name': '物料维护',
                'verbose_name_plural': '物料维护',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=20, unique=True, verbose_name='取餐码')),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='总价')),
                ('status', models.CharField(choices=[('PENDING', '待处理'), ('ACCEPTED', '已接单'), ('MAKING', '制作中'), ('READY', '请取餐'), ('DONE', '已完成')], default='PENDING', max_length=10, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='下单时间')),
            ],
            options={
                'verbose_name': '订单主表',
                'verbose_name_plural': '订单主表',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='产品名称')),
                ('category', models.CharField(choices=[('ESPRESSO', '意式咖啡'), ('POUROVER', '手冲咖啡'), ('NON-CAFFEINE', '非咖啡因饮品'), ('SPECIAL', '特调')], default='ESPRESSO', max_length=20, verbose_name='产品分类')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='基础价格')),
                ('description', models.TextField(blank=True, verbose_name='产品介绍')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='产品照片')),
                ('is_available', models.BooleanField(default=True, verbose_name='是否上架')),
                ('allow_bean_selection', models.BooleanField(default=False, verbose_name='支持自选豆子')),
                ('available_temps', models.CharField(blank=True, help_text='勾选此产品支持的温度及冰量', max_length=200, verbose_name='可选温度/冰量配置')),
                ('available_sugars', models.CharField(blank=True, help_text='勾选此产品支持的甜度等级', max_length=200, verbose_name='可选甜度配置')),
                ('linked_beans', models.ManyToManyField(blank=True, help_text="只有在物料管理中类别为'咖啡豆'的项才会显示在这里", limit_choices_to={'category': 'BEAN'}, to='demo_orders.material', verbose_name='可选咖啡豆种类')),
            ],
            options={
                'verbose_name': '产品管理',
                'verbose_name_plural': '产品管理',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_temp', models.CharField(blank=True, choices=[('HOT', '热'), ('ICE', '正常冰'), ('LESS_ICE', '少冰'), ('NO_ICE', '去冰')], max_length=50, verbose_name='选定温度/冰量')),
                ('selected_sugar', models.CharField(blank=True, choices=[('NORMAL', '标准糖'), ('MORE', '多糖'), ('LESS', '少糖'), ('NONE', '不额外加糖')], max_length=50, verbose_name='选定甜度')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='数量')),
                ('price_at_order', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='成交单价')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='demo_orders.order', verbose_name='所属订单')),
                ('selected_bean', models.ForeignKey(blank=True, limit_choices_to={'category': 'BEAN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='demo_orders.material', verbose_name='选定豆种')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='demo_orders.product', verbose_name='产品名称')),
            ],
            options={
                'verbose_name': '订单明细',
                'verbose_name_plural': '订单明细',
            },
        ),
    ]
