# Generated by Django 5.2.11 on 2026-03-14 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_orders', '0002_order_member'),
        ('members', '0002_alter_member_options_alter_member_joined_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'verbose_name': 'Inventory Assets', 'verbose_name_plural': 'Inventory Assets'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Order Records', 'verbose_name_plural': 'Order Records'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Line Item Detail', 'verbose_name_plural': 'Line Item Details'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product Catalog', 'verbose_name_plural': 'Product Catalog'},
        ),
        migrations.AddField(
            model_name='order',
            name='items_json',
            field=models.TextField(blank=True, default='[]'),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_time',
            field=models.CharField(default='立即取餐', max_length=50),
        ),
        migrations.AlterField(
            model_name='material',
            name='category',
            field=models.CharField(choices=[('BEAN', 'Coffee Bean'), ('DAIRY', 'Dairy Products'), ('FOOD', 'Food Ingredients'), ('NON_FOOD', 'Non-Food Assets')], max_length=20, verbose_name='Material Category'),
        ),
        migrations.AlterField(
            model_name='material',
            name='expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Expiry Date (Perishables Only)'),
        ),
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Material Name'),
        ),
        migrations.AlterField(
            model_name='material',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Unit Price'),
        ),
        migrations.AlterField(
            model_name='material',
            name='quantity',
            field=models.PositiveIntegerField(help_text='Unit: Grams (Beans), Cartons (Dairy), Units (Others).', verbose_name='Stock Quantity'),
        ),
        migrations.AlterField(
            model_name='material',
            name='roast_level',
            field=models.CharField(blank=True, choices=[('DARK', 'Dark Roast'), ('MEDIUM', 'Medium Roast'), ('LIGHT', 'Light Roast')], max_length=10, null=True, verbose_name='Roast Profile (Beans Only)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Order Timestamp'),
        ),
        migrations.AlterField(
            model_name='order',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.member', verbose_name='Member'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(max_length=20, unique=True, verbose_name='Pick-up Code'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Confirmed'), ('MAKING', 'In Progress'), ('READY', 'Ready for Pickup'), ('DONE', 'Completed')], default='PENDING', max_length=20, verbose_name='Order Status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Total Amount'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='demo_orders.order', verbose_name='Order Reference'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price_at_order',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Transaction Price'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='demo_orders.product', verbose_name='Product Name'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='selected_bean',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 'BEAN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='demo_orders.material', verbose_name='Selected Bean'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='selected_sugar',
            field=models.CharField(blank=True, choices=[('NORMAL', 'Standard Sweetness'), ('MORE', 'Extra Sweetness'), ('LESS', 'Reduced Sweetness'), ('NONE', 'No Added Sugar')], max_length=50, verbose_name='Selected Sweetness'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='selected_temp',
            field=models.CharField(blank=True, choices=[('HOT', 'Hot'), ('ICE', 'Standard Ice'), ('LESS_ICE', 'Less Ice'), ('NO_ICE', 'No Ice')], max_length=50, verbose_name='Selected Temp/Ice'),
        ),
        migrations.AlterField(
            model_name='product',
            name='allow_bean_selection',
            field=models.BooleanField(default=False, verbose_name='Enable Bean Selection'),
        ),
        migrations.AlterField(
            model_name='product',
            name='available_sugars',
            field=models.CharField(blank=True, help_text='Select supported sweetness levels for this product.', max_length=200, verbose_name='Sweetness Level Options'),
        ),
        migrations.AlterField(
            model_name='product',
            name='available_temps',
            field=models.CharField(blank=True, help_text='Select supported ice and temperature levels for this product.', max_length=200, verbose_name='Temperature/Ice Options'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('ESPRESSO', 'Espresso-Based'), ('POUROVER', 'Filter / Hand-Brewed'), ('NON-CAFFEINE', 'Non-Caffeinated'), ('SPECIAL', 'Signature Specials')], default='ESPRESSO', max_length=20, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Product Image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Availability'),
        ),
        migrations.AlterField(
            model_name='product',
            name='linked_beans',
            field=models.ManyToManyField(blank=True, help_text="Only materials categorized as 'Coffee Bean' will be listed here.", limit_choices_to={'category': 'BEAN'}, to='demo_orders.material', verbose_name='Available Coffee Beans'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Product Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Base Price'),
        ),
    ]
