# Generated by Django 5.2.11 on 2026-03-14 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_orders', '0004_simplify_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Expiry Date'),
        ),
        migrations.AlterField(
            model_name='material',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Stock Quantity'),
        ),
        migrations.AlterField(
            model_name='material',
            name='roast_level',
            field=models.CharField(blank=True, choices=[('DARK', 'Dark Roast'), ('MEDIUM', 'Medium Roast'), ('LIGHT', 'Light Roast')], max_length=10, null=True, verbose_name='Roast Profile'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(max_length=20, unique=True, verbose_name='Order No.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='available_sugars',
            field=models.CharField(blank=True, max_length=200, verbose_name='Sweetness Level Options'),
        ),
        migrations.AlterField(
            model_name='product',
            name='available_temps',
            field=models.CharField(blank=True, max_length=200, verbose_name='Temperature/Ice Options'),
        ),
        migrations.AlterField(
            model_name='product',
            name='linked_beans',
            field=models.ManyToManyField(blank=True, limit_choices_to={'category': 'BEAN'}, to='demo_orders.material', verbose_name='Available Coffee Beans'),
        ),
    ]
