# Generated by Django 5.2.11 on 2026-02-22 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='员工姓名')),
                ('phone', models.CharField(blank=True, max_length=11, verbose_name='联系电话')),
            ],
            options={
                'verbose_name': '员工信息',
                'verbose_name_plural': '员工信息',
            },
        ),
        migrations.CreateModel(
            name='WeeklySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(1, '周一'), (2, '周二'), (3, '周三'), (4, '周四'), (5, '周五'), (6, '周六'), (7, '周日')], verbose_name='星期几')),
                ('start_time', models.TimeField(verbose_name='上班时间')),
                ('end_time', models.TimeField(verbose_name='下班时间')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.staff', verbose_name='员工')),
            ],
            options={
                'verbose_name': '排班设置',
                'verbose_name_plural': '排班设置',
            },
        ),
        migrations.DeleteModel(
            name='StaffShift',
        ),
    ]
