# Generated by Django 5.2.11 on 2026-02-22 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('student_id', models.CharField(max_length=20, unique=True, verbose_name='学号')),
                ('phone', models.CharField(max_length=11, verbose_name='联系电话')),
                ('level', models.CharField(choices=[('GOLD', '金牌会员'), ('SILVER', '银牌会员'), ('BRONZE', '铜牌会员')], default='BRONZE', max_length=10, verbose_name='会员等级')),
                ('points', models.IntegerField(default=0, verbose_name='积分余额')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='入会时间')),
            ],
            options={
                'verbose_name': '会员管理',
                'verbose_name_plural': '会员管理',
            },
        ),
    ]
