# Generated by Django 5.2.11 on 2026-03-14 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name': 'Member Management', 'verbose_name_plural': 'Member Management'},
        ),
        migrations.AlterField(
            model_name='member',
            name='joined_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Time'),
        ),
        migrations.AlterField(
            model_name='member',
            name='level',
            field=models.CharField(choices=[('GOLD', 'Gold'), ('SILVER', 'Sliver'), ('BRONZE', 'Bronze')], default='BRONZE', max_length=10, verbose_name='level'),
        ),
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.CharField(max_length=11, verbose_name='Contact Number'),
        ),
        migrations.AlterField(
            model_name='member',
            name='points',
            field=models.IntegerField(default=0, verbose_name='Credit'),
        ),
        migrations.AlterField(
            model_name='member',
            name='student_id',
            field=models.CharField(max_length=20, unique=True, verbose_name='Student ID'),
        ),
    ]
