# Generated by Django 4.2.20 on 2026-04-16 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_member_nickname_member_openid'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='avatar',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='头像URL'),
        ),
    ]
