# Generated by Django 4.2.20 on 2026-04-16 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_member_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='level',
            field=models.CharField(choices=[('GOLD', 'Gold'), ('SLIVER', 'Sliver'), ('BRONZE', 'Bronze')], default='BRONZE', max_length=10, verbose_name='level'),
        ),
    ]
