# Generated by Django 4.2.30 on 2026-05-24 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_alter_member_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={},
        ),
    ]
