# Generated by Django 5.2.11 on 2026-02-22 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Global Sales Overview', max_length=100, verbose_name='报表标题')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
            ],
            options={
                'verbose_name': 'Reporting System (BI)',
                'verbose_name_plural': 'Reporting System (BI)',
            },
        ),
    ]
