"""
Django settings for mysite project.
Generated by 'django-admin startproject' using Django 4.2.20.
"""
from pathlib import Path
import os
import pymysql
pymysql.install_as_MySQLdb()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def load_dotenv(path):
    """Load simple KEY=VALUE pairs from a local .env file if present."""
    if not path.exists():
        return
    for raw_line in path.read_text(encoding='utf-8').splitlines():
        line = raw_line.strip()
        if not line or line.startswith('#') or '=' not in line:
            continue
        key, value = line.split('=', 1)
        os.environ.setdefault(key.strip(), value.strip().strip('"').strip("'"))


def env_bool(name, default=False):
    value = os.getenv(name)
    if value is None:
        return default
    return value.lower() in {'1', 'true', 'yes', 'on'}


def env_list(name, default=None):
    value = os.getenv(name)
    if not value:
        return default or []
    return [item.strip() for item in value.split(',') if item.strip()]


load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-dev-only-change-me')

# SECURITY WARNING: don't run with debug turned on in production!
# 建議在雲托管環境變數中控制：DJANGO_DEBUG=True/False
DEBUG = env_bool('DJANGO_DEBUG', True)

ALLOWED_HOSTS = env_list(
    'DJANGO_ALLOWED_HOSTS',
    ['localhost', '127.0.0.1', '0.0.0.0', '.tcloudbase.com', '.run.tcloudbase.com']
)

# 新增這一行：信任你的雲托管域名（包含 https:// 前綴）
# 微信小程序走 API，不需要瀏覽器 CSRF。
# 只保留 Admin 後台自己用的 trusted origins。
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:8000',
    'http://127.0.0.1:8000',
    'https://django-ye5o-236914-8-1414261904.sh.run.tcloudbase.com',
    'https://*.run.tcloudbase.com',
    'https://*.tcloudbase.com',
] + env_list('DJANGO_CSRF_TRUSTED_ORIGINS')

# Application definition
INSTALLED_APPS = [
    'simpleui',                         # 放在 admin 之前，讓 SimpleUI 覆蓋預設 admin
    'django.contrib.admin',
    'corsheaders',
    'rest_framework',
    'whitenoise.runserver_nostatic',    # 防止開發模式下 Django 自己 serve static
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # 你的自訂 app
    'demo_orders',
    'members',
    'feedback',
    'staff',
    'analytics',
    'coupons',
    'ai_assistant',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',           # 放在最前面
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',      # 用來 serve static files
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# CORS 設定（開發方便，生產可收緊）
CORS_ALLOW_ALL_ORIGINS = env_bool('DJANGO_CORS_ALLOW_ALL_ORIGINS', DEBUG)
CORS_ALLOWED_ORIGINS = env_list('DJANGO_CORS_ALLOWED_ORIGINS')

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'


# Database
# 本地用 MySQL（與雲端一致），透過 .env 或環境變數設定連線資訊
DB_NAME = os.getenv('DB_NAME', 'bean_butler')
DB_USER = os.getenv('DB_USER', 'root')
DB_PASSWORD = os.getenv('DB_PASSWORD', '')
DB_HOST = os.getenv('DB_HOST', '127.0.0.1')
DB_PORT = os.getenv('DB_PORT', '3306')
MYSQL_ADDRESS = os.getenv('MYSQL_ADDRESS')
if MYSQL_ADDRESS and ':' in MYSQL_ADDRESS:
    DB_HOST, DB_PORT = MYSQL_ADDRESS.rsplit(':', 1)
elif MYSQL_ADDRESS:
    DB_HOST = MYSQL_ADDRESS

# 微信雲托管會自動注入 MYSQL_ADDRESS 這個環境變數
if os.environ.get('MYSQL_ADDRESS'):
    # 🌩️ 雲端環境配置
    # Database
    # 直接強制寫死雲端 MySQL 的連線資訊
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': DB_NAME,
            'USER': DB_USER,
            'PASSWORD': DB_PASSWORD,
            'HOST': DB_HOST,
            'PORT': DB_PORT,
            'OPTIONS': {
                'charset': 'utf8mb4',
                # 💡 這一行是關鍵：強制所有會話變量同步為 utf8mb4
                'init_command': "SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci",
            },
        }
    }

else:
    # 💻 本地開發環境配置 (保留你原本連 XAMPP 的設定)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': DB_NAME,
            'USER': DB_USER,
            'PASSWORD': DB_PASSWORD,
            'HOST': DB_HOST,
            'PORT': DB_PORT,
            'OPTIONS': {
                'charset': 'utf8mb4',
                'init_command': "SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci",
            },
        }
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# SimpleUI 自訂設定
SIMPLEUI_HOME_INFO = [
    {'name': 'Today Total Orders', 'icon': 'fas fa-shopping-cart', 'value': '25'},
    {'name': 'Orders Completed', 'icon': 'fas fa-check-circle', 'value': '18'},
    {'name': 'Today Revenue', 'icon': 'fas fa-yen-sign', 'value': '840.00'},
    {'name': 'New Members', 'icon': 'fas fa-user-plus', 'value': '5'},
]

SIMPLEUI_HOME_QUICK = True
SIMPLEUI_HOME_ACTION = True
SIMPLEUI_HOME_INFO = False
SIMPLEUI_ANALYSIS = False

SIMPLEUI_CONFIG = {
    'system_keep': False,
    'menu_display': ['Operations', 'Reporting', 'AI Recommendations', 'System'],
    'menus': [
        {
            'name': 'Operations',
            'icon': 'fas fa-tasks',
            'models': [
                {'name': 'Order Station', 'icon': 'fas fa-rocket', 'url': '/admin/demo_orders/order/station/'},
                {'name': 'Order History', 'icon': 'fas fa-history', 'url': '/admin/demo_orders/order/'},
                {'name': 'Product Maintenance', 'icon': 'fas fa-coffee', 'url': '/admin/demo_orders/product/'},
                {'name': 'Material Maintenance', 'icon': 'fas fa-box', 'url': '/admin/demo_orders/material/'},
                {'name': 'Member Management', 'icon': 'fas fa-users', 'url': '/admin/members/member/'},
                {'name': 'Customer Feedback', 'icon': 'fas fa-comment-dots', 'url': '/admin/feedback/feedback/'},
                {'name': 'Coupon Management', 'icon': 'fas fa-ticket-alt', 'url': '/admin/coupons/coupon/'},
            ]
        },
        {
            'name': 'Reporting',
            'icon': 'fas fa-chart-line',
            'models': [
                {'name': 'Data Dashboard', 'icon': 'fas fa-tachometer-alt', 'url': '/admin/dashboard/'}
            ]
        },
        {
            'name': 'AI Recommendations',
            'icon': 'fas fa-robot',
            'models': [
                {'name': 'AI Recommendations', 'icon': 'fas fa-magic', 'url': '/admin/demo_orders/recommendation/'},
                {'name': 'Recommender Run Log', 'icon': 'fas fa-history', 'url': '/admin/demo_orders/recommenderrunlog/'},
            ]
        },
    ]
}


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Macau'
USE_I18N = True
USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# 使用 WhiteNoise 壓縮與快取靜態文件
# 本地開發用預設 storage，不需要先跑 collectstatic
if DEBUG:
    STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'
else:
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


# 1. 定義基礎的 Media 路徑
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# 2. 根據環境動態生成 MEDIA_URL
# 微信雲托管會注入環境變數，這裡我們判斷是否在雲端
if os.environ.get('MYSQL_ADDRESS'):
    # 🌩️ 雲端環境：使用完整的 HTTPS 域名
    # 這裡建議直接使用你 CSRF 列表中的那個域名
    # 務必確保結尾有斜槓 /
    MEDIA_URL = os.getenv(
        'MEDIA_URL',
        'https://beanbulter-236914-8-1414261904.sh.run.tcloudbase.com/media/'
    )
else:
    # 💻 本地環境：使用相對路徑
    MEDIA_URL = os.getenv('MEDIA_URL', '/media/')

# 其他設定
X_FRAME_OPTIONS = 'SAMEORIGIN'

# REST Framework 設定（無認證/權限限制，適合開發）
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [],
    'DEFAULT_PERMISSION_CLASSES': [],
}

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
