# Generated by Django 5.2.11 on 2026-02-22 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='留言内容')),
                ('reply', models.TextField(blank=True, null=True, verbose_name='店员回复')),
                ('is_processed', models.BooleanField(default=False, verbose_name='是否已处理')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member', verbose_name='会员')),
            ],
        ),
    ]
