# Generated by Django 5.2.11 on 2026-02-23 03:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-created_at'], 'verbose_name': '会员留言与反馈', 'verbose_name_plural': '会员留言与反馈'},
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='content',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='is_processed',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='reply',
        ),
        migrations.AddField(
            model_name='feedback',
            name='admin_reply',
            field=models.TextField(blank=True, help_text='管理员填写的反馈内容，将传送至点单端', null=True, verbose_name='后台反馈/回复'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='留言时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='is_replied',
            field=models.BooleanField(default=False, verbose_name='是否已反馈'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='replied_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='回复时间'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='user_message',
            field=models.TextField(default=django.utils.timezone.now, help_text='会员从点单端发送的内容', verbose_name='会员留言'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedback',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member', verbose_name='所属会员'),
        ),
    ]
