# Generated by Django 5.2.11 on 2026-03-14 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_alter_feedback_options_remove_feedback_content_and_more'),
        ('members', '0002_alter_member_options_alter_member_joined_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-created_at'], 'verbose_name': 'Customer Feedback & Interaction', 'verbose_name_plural': 'Customer Feedback & Interaction'},
        ),
        migrations.AlterField(
            model_name='feedback',
            name='admin_reply',
            field=models.TextField(blank=True, help_text='Administrative response/feedback to be transmitted back to the member.', null=True, verbose_name='Official Resolution'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Submission Timestamp'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='is_replied',
            field=models.BooleanField(default=False, verbose_name='Response Status'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member', verbose_name='Associated Member'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='replied_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Resolution Timestamp'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='user_message',
            field=models.TextField(help_text='Original message submitted by the member from the ordering terminal.', verbose_name='Customer Inquiry'),
        ),
    ]
